### ISSUE TITLE
Add support to select multiple student loans

### ISSUE THREAD

**Issue by james-banks** [wozniakpawel/cooltaxtool#19]
Add the ability to add multiple student loans to better reflect the possible situations of users. 

Eg. The ability to select Plan 2 *and* Postgraduate for people whom have both.

**Comment by wozniakpawel** [comment]
It looks like changing from a drop-down to a multiple selection list would be better. Some people have odd combinations of student loans, e.g. plan 1 and plan 2 if they studied at two different universities. Multi-selection should be able to cover that.
