### ISSUE TITLE
Add ability to have decimal places in pension contributions

### ISSUE THREAD

**Issue by Ross-mc** [wozniakpawel/cooltaxtool#20]
I currently contribute to my pension an amount of x.5%

Currently the form only allows integer pension contributions.

I would be happy to raise a PR if it would be helpful.

**Comment by wozniakpawel** [comment]
Feel free to raise a PR if you know how to fix it!

**Comment by Donbasilpeter** [comment]
hello there. I would like to look into this problem.Could you assign this in my name?
