### ISSUE TITLE
Add sponsorships

### ISSUE THREAD

**Issue by bee-san** [wozniakpawel/cooltaxtool#22]
Sign up to github sponsors or something :) https://github.com/sponsors if you want some donations for working on this! <3 :)

**Comment by wozniakpawel** [comment]
Thanks, didn't know about that! I just signed in, might help with the costs of hosting the page.

**Comment by ThePotato97** [comment]
> Thanks, didn't know about that! I just signed in, might help with the costs of hosting the page.

You're not using GitHub pages?

**Comment by wozniakpawel** [comment]
Yeah, I wasn't sure how easy it is to host a React app with Plotly graphs on github pages, so I just went straight for Netlify.
