### ISSUE TITLE
Stick footer to the bottom of the page

### ISSUE THREAD

**Issue by wozniakpawel** [wozniakpawel/cooltaxtool#5]
Currently it is at the bottom of the tallest component on the page

**Comment by Sky-De** [comment]
Do you mean you want it stick to the bottom of view port(screen)?

**Comment by wozniakpawel** [comment]
Hmm, actually probably no because the footer is quite large, and it would impede view.
To make it look better it probably just needs a bit of padding on the top, so that it doesn't appear too close to the element above.

**Comment by Sky-De** [comment]
Ok
Assign it to me, i will take a look as soon as i got time

**Comment by wozniakpawel** [comment]
Sorry, got it done already but I promise I won't touch any other issues for a couple of weeks so feel free to have a shot at any of the other ones :)

**Comment by wozniakpawel** [comment]
Reopening…
Actually on the second thought, could you make it stick to the bottom of view port but only if there is not enough elements to fill the viewport (so on a large screen with few components)? It currently sits somewhere in the middle of the view port.
On smaller screens I’d like it to behave as it currently does.
